### ISSUE TITLE
Great Job!

### ISSUE THREAD

**Issue by petrk94** [rohitpaulk/todoist-tribute#10]
Hello,

it looks really impressive and similar to Todoist :)
I would like to know what it needs to support you?
Why not making user account function for multiple users.

Thanks

**Comment by petrk94** [comment]
and just saw it in the demo, the finished tasks disappear, I would like to have a archive option, where the finished tasks are visible

**Comment by rohitpaulk** [comment]
Hey @petrk94. This is one among many features that isn't available yet - follow the README for progress (there's a checklist at the end).
